// Code generated by protoc-gen-gin-http. DO NOT EDIT.
package v1

import (
	"github.com/gin-gonic/gin"
	empty "github.com/golang/protobuf/ptypes/empty"
	"github.com/zngue/zng_app/db/api"
	"github.com/zngue/zng_app/pkg/bind"
	"github.com/zngue/zng_app/pkg/validate"
)

// 服务操作
const OperationGinCategoryInfo = "api.test.v1.Category.Info"
const OperationGinCategoryListPage = "api.test.v1.Category.ListPage"
const OperationGinCategoryList = "api.test.v1.Category.List"
const OperationGinCategoryAdd = "api.test.v1.Category.Add"
const OperationGinCategoryUpdate = "api.test.v1.Category.Update"
const OperationGinCategoryDelete = "api.test.v1.Category.Delete"
const OperationGinCategoryContent = "api.test.v1.Category.Content"
const OperationGinCategoryStatus = "api.test.v1.Category.Status"

// 服务url
const OperationGinUrlCategoryInfo = "/v1/category/info"
const OperationGinUrlCategoryListPage = "/v1/category/listPage"
const OperationGinUrlCategoryList = "/v1/category/list"
const OperationGinUrlCategoryAdd = "/v1/category/add"
const OperationGinUrlCategoryUpdate = "/v1/category/update"
const OperationGinUrlCategoryDelete = "/v1/category/delete"
const OperationGinUrlCategoryContent = "/v1/category/content"
const OperationGinUrlCategoryStatus = "/v1/category/status"

// 服务注册
func RegisterCategoryGinRouter(router *gin.Engine, srv CategoryServer) {
	router.GET(OperationGinUrlCategoryInfo, _Category_Info0_GIN_HTTP_Handler(srv))
	router.GET(OperationGinUrlCategoryListPage, _Category_ListPage0_GIN_HTTP_Handler(srv))
	router.GET(OperationGinUrlCategoryList, _Category_List0_GIN_HTTP_Handler(srv))
	router.POST(OperationGinUrlCategoryAdd, _Category_Add0_GIN_HTTP_Handler(srv))
	router.POST(OperationGinUrlCategoryUpdate, _Category_Update0_GIN_HTTP_Handler(srv))
	router.POST(OperationGinUrlCategoryDelete, _Category_Delete0_GIN_HTTP_Handler(srv))
	router.GET(OperationGinUrlCategoryContent, _Category_Content0_GIN_HTTP_Handler(srv))
	router.POST(OperationGinUrlCategoryStatus, _Category_Status0_GIN_HTTP_Handler(srv))
}

func _Category_Info0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryInfoRequest
			err error
			rs  *CategoryInfoReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryInfo)
		rs, err = srv.Info(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_ListPage0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryListRequest
			err error
			rs  *CategoryListReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryListPage)
		rs, err = srv.ListPage(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_List0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryListRequest
			err error
			rs  *CategoryInfoListReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryList)
		rs, err = srv.List(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_Add0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryAddRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryAdd)
		rs, err = srv.Add(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_Update0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryUpdateRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryUpdate)
		rs, err = srv.Update(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_Delete0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryDeleteRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryDelete)
		rs, err = srv.Delete(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

func _Category_Content0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryContentRequest
			err error
			rs  *CategoryContentReply
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryContent)
		rs, err = srv.Content(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}

// StatusStatus
func _Category_Status0_GIN_HTTP_Handler(srv CategoryGinHttpService) gin.HandlerFunc {
	return func(c *gin.Context) {
		var (
			in  CategoryStatusRequest
			err error
			rs  *empty.Empty
		)
		err = bind.Bind(c, &in)
		if err != nil {
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(c, err, rs)
			return
		}
		ctx := c.Request.Context()
		ctx = bind.NewServerContext(ctx, c, OperationGinCategoryStatus)
		rs, err = srv.Status(ctx, &in)
		api.DataApiWithErr(c, err, rs)
	}
}
