// Code generated by protoc-gen-gin-http. DO NOT EDIT.
package v1

import (
	"github.com/zngue/zng_app/db/api"
	"context"
	"github.com/zngue/zng_app/pkg/validate"
	"github.com/zngue/zng_app/pkg/bind"
	"github.com/gin-gonic/gin"
)

const OperationCategoryInfoHttpGin = "/v1/category/info"
const OperationCategoryListPageHttpGin = "/v1/category/listPage"
const OperationCategoryListHttpGin = "/v1/category/list"
const OperationCategoryAddHttpGin = "/v1/category/add"
const OperationCategoryUpdateHttpGin = "/v1/category/update"
const OperationCategoryDeleteHttpGin = "/v1/category/delete"
const OperationCategoryContentHttpGin = "/v1/category/content"
const OperationCategoryStatusHttpGin = "/v1/category/status"

// CategoryGinHandler --- defines a Gin HTTP handler.
func RegisterCategoryGinHandler(r *gin.RouterGroup, srv CategoryServer) {
	var routes = r.Group("/")
	routes.GET("/v1/category/info", _Category_Info0_GIN_HTTP_Handler(srv))
	routes.GET("/v1/category/listPage", _Category_ListPage0_GIN_HTTP_Handler(srv))
	routes.GET("/v1/category/list", _Category_List0_GIN_HTTP_Handler(srv))
	routes.POST("/v1/category/add", _Category_Add0_GIN_HTTP_Handler(srv))
	routes.POST("/v1/category/update", _Category_Update0_GIN_HTTP_Handler(srv))
	routes.POST("/v1/category/delete", _Category_Delete0_GIN_HTTP_Handler(srv))
	routes.GET("/v1/category/content", _Category_Content0_GIN_HTTP_Handler(srv))
	//Status
	routes.POST("/v1/category/status", _Category_Status0_GIN_HTTP_Handler(srv))
}

func NewcategoryGinClient(srv bind.ClientServer) (server CategoryServer) {
	return &categoryGinClient{
		srv: srv,
	}
}

type categoryGinClient struct {
	srv bind.ClientServer
	UnimplementedCategoryServer
}

func (c *categoryGinClient) Info(ctx context.Context, req *CategoryInfoRequest) (rs *CategoryInfoReply, err error) {
	err = c.srv.GET(ctx, OperationCategoryInfoHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) ListPage(ctx context.Context, req *CategoryListRequest) (rs *CategoryListReply, err error) {
	err = c.srv.GET(ctx, OperationCategoryListPageHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) List(ctx context.Context, req *CategoryListRequest) (rs *CategoryInfoListReply, err error) {
	err = c.srv.GET(ctx, OperationCategoryListHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) Add(ctx context.Context, req *CategoryAddRequest) (rs *Empty, err error) {
	err = c.srv.POST(ctx, OperationCategoryAddHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) Update(ctx context.Context, req *CategoryUpdateRequest) (rs *Empty, err error) {
	err = c.srv.POST(ctx, OperationCategoryUpdateHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) Delete(ctx context.Context, req *CategoryDeleteRequest) (rs *Empty, err error) {
	err = c.srv.POST(ctx, OperationCategoryDeleteHttpGin, req, &rs)
	return
}
func (c *categoryGinClient) Content(ctx context.Context, req *CategoryContentRequest) (rs *CategoryContentReply, err error) {
	err = c.srv.GET(ctx, OperationCategoryContentHttpGin, req, &rs)
	return
}

// Status
func (c *categoryGinClient) Status(ctx context.Context, req *CategoryStatusRequest) (rs *Empty, err error) {
	err = c.srv.POST(ctx, OperationCategoryStatusHttpGin, req, &rs)
	return
}

func _Category_Info0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryInfoRequest
			err error
			rs  *CategoryInfoReply
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryInfoHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Info(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_ListPage0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryListRequest
			err error
			rs  *CategoryListReply
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryListPageHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.ListPage(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_List0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryListRequest
			err error
			rs  *CategoryInfoListReply
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryListHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.List(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_Add0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryAddRequest
			err error
			rs  *Empty
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryAddHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Add(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_Update0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryUpdateRequest
			err error
			rs  *Empty
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryUpdateHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Update(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_Delete0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryDeleteRequest
			err error
			rs  *Empty
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryDeleteHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Delete(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

func _Category_Content0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryContentRequest
			err error
			rs  *CategoryContentReply
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryContentHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Content(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}

// Status
func _Category_Status0_GIN_HTTP_Handler(srv CategoryServer) gin.HandlerFunc {
	return func(ctx *gin.Context) {
		var (
			in  CategoryStatusRequest
			err error
			rs  *Empty
		)
		err = bind.Bind(ctx, &in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(427))
			return
		}
		err = validate.Validate(&in)
		if err != nil {
			api.DataApiWithErr(ctx, err, nil, api.Code(422))
			return
		}
		ctx.Set("operation", OperationCategoryStatusHttpGin)
		var c = context.Background()
		c = bind.NewServerContext(c, ctx)
		rs, err = srv.Status(c, &in)
		api.DataApiWithErr(ctx, err, rs)
	}
}
