// Code generated by protoc-gen-gin-http. DO NOT EDIT.
package v1

import (
	"github.com/gin-gonic/gin"
	"github.com/zngue/zng_app/pkg/router"
	"github.com/zngue/zng_app/pkg/validate"
)

type TestGinHttpRouterService struct {
	srv    TestGinHttpService
	router *gin.RouterGroup
}

func (s *TestGinHttpRouterService) Register() []router.IRouter {
	return router.ApiServiceFn(
		router.ApiGetFn(s.router, "/v1/test/info", _Test_Info0_GIN_HTTP_Handler(s.srv)),
		router.ApiGetFn(s.router, "/v1/test/list", _Test_List0_GIN_HTTP_Handler(s.srv)),
		router.ApiPostFn(s.router, "/v1/test/create", _Test_Create0_GIN_HTTP_Handler(s.srv)),
	)
}

func RegisterTestGinHttpRouterService(
	api *gin.RouterGroup,
	srv TestGinHttpService,
) router.IApiService {
	return &TestGinHttpRouterService{
		srv:    srv,
		router: api,
	}
}

type TestGinHttpService interface {
	Info(ctx *gin.Context, req *GetTestRequest) (rs *GetTestReply, err error)
	List(ctx *gin.Context, req *GetListTestRequest) (rs *GetTestReply, err error)
	Create(ctx *gin.Context, req *GetTestRequest) (rs *GetTestReply, err error)
}

func _Test_Info0_GIN_HTTP_Handler(srv TestGinHttpService) router.Fn {
	return func(ctx *gin.Context) (rs any, err error) {
		var in *GetTestRequest
		if err = ctx.BindJSON(&in); err != nil {
			return
		}
		err = validate.Validate(in)
		if err != nil {
			return
		}
		rs, err = srv.Info(ctx, in)
		return
	}
}

func _Test_List0_GIN_HTTP_Handler(srv TestGinHttpService) router.Fn {
	return func(ctx *gin.Context) (rs any, err error) {
		var in *GetListTestRequest
		if err = ctx.BindJSON(&in); err != nil {
			return
		}
		err = validate.Validate(in)
		if err != nil {
			return
		}
		rs, err = srv.List(ctx, in)
		return
	}
}

func _Test_Create0_GIN_HTTP_Handler(srv TestGinHttpService) router.Fn {
	return func(ctx *gin.Context) (rs any, err error) {
		var in *GetTestRequest
		if err = ctx.ShouldBind(&in); err != nil {
			return
		}
		err = validate.Validate(in)
		if err != nil {
			return
		}
		rs, err = srv.Create(ctx, in)
		return
	}
}
