// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/test/v1/user.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AbcUserRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AbcUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AbcUserRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AbcUserRequestMultiError,
// or nil if none found.
func (m *AbcUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AbcUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return AbcUserRequestMultiError(errors)
	}

	return nil
}

// AbcUserRequestMultiError is an error wrapping multiple validation errors
// returned by AbcUserRequest.ValidateAll() if the designated constraints
// aren't met.
type AbcUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AbcUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AbcUserRequestMultiError) AllErrors() []error { return m }

// AbcUserRequestValidationError is the validation error returned by
// AbcUserRequest.Validate if the designated constraints aren't met.
type AbcUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AbcUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AbcUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AbcUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AbcUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AbcUserRequestValidationError) ErrorName() string { return "AbcUserRequestValidationError" }

// Error satisfies the builtin error interface
func (e AbcUserRequestValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = AbcUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AbcUserRequestValidationError{}

// Validate checks the field values on AbcUserReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AbcUserReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AbcUserReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AbcUserReplyMultiError, or
// nil if none found.
func (m *AbcUserReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AbcUserReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Image

	if len(errors) > 0 {
		return AbcUserReplyMultiError(errors)
	}

	return nil
}

// AbcUserReplyMultiError is an error wrapping multiple validation errors
// returned by AbcUserReply.ValidateAll() if the designated constraints aren't met.
type AbcUserReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AbcUserReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AbcUserReplyMultiError) AllErrors() []error { return m }

// AbcUserReplyValidationError is the validation error returned by
// AbcUserReply.Validate if the designated constraints aren't met.
type AbcUserReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AbcUserReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AbcUserReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AbcUserReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AbcUserReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AbcUserReplyValidationError) ErrorName() string { return "AbcUserReplyValidationError" }

// Error satisfies the builtin error interface
func (e AbcUserReplyValidationError) Error() string {
	if strings.Contains(e.reason, "syMsg") {
		return strings.Trim(e.Reason(), "syMsg")
	}
	return e.field + e.reason
}

var _ error = AbcUserReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AbcUserReplyValidationError{}
