// Code generated by protoc-gen-protoc-gen-gin-http. DO NOT EDIT.
package validate

import (
	"github.com/gin-gonic/gin"
	"github.com/zngue/zng_app/pkg/router"
	"github.com/zngue/zng_app/pkg/validate"
)
