package main

import (
	"flag"
	"fmt"
	"strings"

	"github.com/zngue/zng_tool/app/util"
	"github.com/zngue/zng_tool/cmd/protoc-gen-zng-http/internal"
	googleannotations "github.com/zngue/zng_tool/third_party/google/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

var showVersion = flag.Bool("version", false, "print the version and exit")

func main() {
	flag.Parse()
	if *showVersion {
		fmt.Printf("protoc-gen-zng-http %v\n", "v2.0.0")
		return
	}
	opts := &protogen.Options{}
	opts.Run(func(gen *protogen.Plugin) error {
		for _, file := range gen.Files {
			if len(file.Services) == 0 {
				continue
			}
			fileName := file.GeneratedFilenamePrefix + ".http.pb.go"
			g := gen.NewGeneratedFile(fileName, file.GoImportPath)
			g.P("// Code generated by protoc-gen-zng-http. DO NOT EDIT.")
			g.P("package ", file.GoPackageName)
			g.P()
			for _, service := range file.Services {
				sd := &internal.ServiceDesc{
					ServiceType: service.GoName,
					Comment:     string(service.Comments.Leading),
					ServiceName: string(service.Desc.FullName()),
					Metadata:    file.Desc.Path(),
				}
				for _, method := range service.Methods {
					if method.Desc.IsStreamingClient() {
						continue
					}
					isStreaming := method.Desc.IsStreamingServer()
					comment := method.Comments.Leading.String() + method.Comments.Trailing.String()
					if comment != "" {
						comment = "// " + method.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
					}
					rule, _ := proto.GetExtension(method.Desc.Options(), googleannotations.E_Http).(*googleannotations.HttpRule)
					path, useMethod, body := internal.RequestInfo(rule, util.LowerFirst(service.GoName), util.LowerFirst(method.GoName))
					sd.Methods = append(sd.Methods, &internal.MethodDesc{
						Name:         method.GoName,
						OriginalName: string(method.Desc.Name()),
						Request:      g.QualifiedGoIdent(method.Input.GoIdent),
						Reply:        g.QualifiedGoIdent(method.Output.GoIdent),
						Comment:      comment,
						Path:         internal.ToMuxPath(path),
						Method:       useMethod,
						Body:         body,
						Operation:    string(service.Desc.FullName()) + "." + string(method.Desc.Name()),
						IsStreaming:  isStreaming,
					})
				}
				g.P(sd.Execute())
			}
		}
		return nil
	})
}
